{
 "title": "Triton Inference Server Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "model",
    "query": {
     "query": "label_values(nv_inference_count, model)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average success rate ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(model) (((changes(nv_inference_request_success{model=\"$model\"}[5m]) + changes(nv_inference_request_failure{model=\"$model\"}[5m])) > 0) * increase(nv_inference_request_success{model=\"$model\"}[5m]) / (increase(nv_inference_request_success{model=\"$model\"}[5m]) + increase(nv_inference_request_failure{model=\"$model\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(gpu_uuid) (avg_over_time(nv_gpu_utilization[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of inferences per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg by(model) (rate(nv_inference_count{model=\"$model\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average inference duration (ms)",
   "type": "timeseries",
   "description": "Average inference duration per second, given in ms format",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(model) (rate(nv_inference_request_duration_us{model=\"$model\"}[5m])) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of executions per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg by(model) (rate(nv_inference_exec_count{model=\"$model\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average inference queuing duration (ms)",
   "type": "timeseries",
   "description": "Average inference queuing duration per second, given in ms format",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(model) (rate(nv_inference_queue_duration_us{model=\"$model\"}[5m])) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average compute input duration (ms)",
   "type": "timeseries",
   "description": "Average compute input  duration per second, given in ms format",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(model) (rate(nv_inference_compute_input_duration_us{model=\"$model\"}[5m])) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average compute inference duration (ms)",
   "type": "timeseries",
   "description": "Average compute inference duration per second, given in ms format",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(model) (rate(nv_inference_compute_infer_duration_us{model=\"$model\"}[5m])) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average compute output duration (ms)",
   "type": "timeseries",
   "description": "Average compute output duration per second, given in ms format",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(model) (rate(nv_inference_compute_output_duration_us{model=\"$model\"}[5m])) / 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}